### PR TITLE
Support multiple targets and add nuspec (become nuget)

### PR DESCRIPTION
**Pull request by kekyo**
Currently not tested by netstandard 1.4 because I don't want to changesets enlarge...

### CODE REVIEW

**Comment by atsushieno** [comment]
Can't these project files be unified in one file now that MSBuild supports multiple profiles within a single project?

**Comment by kekyo** [comment]
Because new msbuild format maybe causes trush :) and I think about I'll support better neutral requirements by PCL.
(But it idea is not required for now because clang is native, it hasn't portability)

I feel it uses new msbuild format if support netstandard1.4, just now. I'll rewrite new format if you agree 
(on net40 and netstandard1.4 .)

**Comment by atsushieno** [comment]
1) PCL: right, I don't see any benefit of having PCL version at this point. Adding extra project files means there are more files to maintain, for slight benefits. Actually same for netstandard. The only beneficial framework would be Xamarin.Mac mobile target and UWP, which I'm quite unsure that neither of us would care at this point :P

2) .NET Core projects would make sense and it can be done in safer manner with new MSBuild format, which would need almost no changes on library updates (well, actually it will be with explicit source specification with wildcards due to the directory structure though). I'm kind of inclined to do it by myself ;-)

3) nuget packaging: I'm not sure if I like the idea of packaging only native .dll without .dylib and .so. At least I will need precompiled binaries for packaging.

**Comment by kekyo** [comment]
1. I forgot support PCL now :)
2. Yes and I feel we can use short format and it's better way.
3. I'm thinking the same way, package contains clang's binary... hmm, clang binaries aren't update frequently so we can containes and not careful... ?
   They can use for nuget simple way because it contains clang binary.
   (I don't know how to deploy multi-platformed native binaries formaly in nuget...)
Strategy:
  May I exclude binaries for first step. Then next step contains binaries.
  (Physical way: we can separate clang binaries from master branch)

**Comment by kekyo** [comment]
Continue #9 only new MSBuild topics.

**Pull request closed without merging**
